services:
  sharkhub-modulo1:
    build:
      context: .
      dockerfile: Dockerfile
    image: sharkhub-modulo2:latest
    container_name: sharkhub_modulo2_web
    restart: unless-stopped
    ports:
      - "8000:80"
    environment:
      - VITE_API_URL=http://localhost:3001
      - VITE_GOOGLE_CLIENT_ID=TU_GOOGLE_CLIENT_ID.apps.googleusercontent.com
